### ISSUE TITLE
Bug - Zombies: Inconsistent team enforcement

### ISSUE THREAD

**Issue by Sonicscream** [atsmith14/BattleBitMinigames#5]
Players are able to respawn as humans after dying. This includes (at least) being killed by zombies or hitting respawn in menu. It occurs seemingly at any time during the match.

**Comment by Bims-sh** [comment]
Fixed in https://github.com/atsmith14/BattleBitMinigames/commit/b677df853c22d2ba348fdf70d319c8bf50e7ab5d
